from selenium import webdriver
from selenium.webdriver.common.by import By

driver= webdriver.Firefox()
driver.get("https://www.seleniumhq.org")
element_id = driver.find_element(By.ID,'announcement-banner')
# element_name = driver.find_element(By.NAME,'q')
element_r_xpath = driver.find_element(By.XPATH,'//*[@id="announcement-banner"]//div//div//div')
element_a_xpath_id = driver.find_element(By.XPATH,'//section[@id="announcement-banner"]')
element_a_xpath_class = driver.find_element(By.XPATH,'//section[@class="alert-static g-0 row -bg-selenium-blue"]')
element_class = driver.find_element(By.CLASS_NAME,'alert-heading.text-center.m-2')
print("My id element is:")
print(element_id)
# print("My name element is:")
# print(nameq)
print("My relative xpath element is:")
print(element_r_xpath)
print("My absolute xpath id element is:")
print(element_a_xpath_id)
print("My absolute xpath class element is:")
print(element_a_xpath_class)
print("My class element is:")
print(element_class)
driver.close()
